name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Chart Releaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Helm Lint
        run: helm lint charts/sample1
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  manual-release:
    name: Manual Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sample-helm-chart

      - name: Helm Lint
        working-directory: sample-helm-chart/charts/sample1
        run: helm lint .

      - name: Helm Package
        working-directory: sample-helm-chart/charts/sample1
        run: helm package .

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: helm-charts
          persist-credentials: false
          repository : mohan-13/helm-charts
          ref: gh-pages

      - name: Copy Helm Archive
        run: cp sample-helm-chart/charts/sample1/*.tgz helm-charts/
      - name: Helm Index
        run: helm repo index --url https://mohan-13.github.io/helm-charts/  helm-charts/
      - name: Commit and Push Chart
        working-directory: helm-charts/
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push https://mohan-13:${{ secrets.PAT}}@github.com/mohan-13/helm-charts.git gh-pages