name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  helm-build-publish:
    name: Helm Build and Publish
    runs-on: ubuntu-latest
    env:
      HELM_CHART_PATH: sample-helm-chart/package/helm/openmrs
      BAHMNI_VERSION: 0.94
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sample-helm-chart

      - name: Update image tag
        run: yq --inplace '.image.tag = "${{env.BAHMNI_VERSION}}-${{github.run_number}}"' $HELM_CHART_PATH/values.yaml
      - name: Helm Lint
        run: helm lint $HELM_CHART_PATH

      - name: Helm Package
        run: helm package $HELM_CHART_PATH --version 1.0.0-${{env.BAHMNI_VERSION}}-${{github.run_number}} --app-version "${{env.BAHMNI_VERSION}}-${{github.run_number}}"

      - name: Checkout Charts Repository
        uses: actions/checkout@v2
        with:
          repository : mohan-13/helm-charts
          ref: gh-pages
          path: helm-charts
          persist-credentials: false

      - name: Copy Helm Archive
        run: cp openmrs-*.tgz helm-charts/openmrs/

      - name: Helm Index
        run: helm repo index --merge helm-charts/index.yaml --url https://mohan-13.github.io/helm-charts/  helm-charts/
      - name: Commit and Push Chart
        working-directory: helm-charts/
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push https://mohan-13:${{ secrets.PAT}}@github.com/mohan-13/helm-charts.git gh-pages