name: Database Setup
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for DB Setup'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - demo
jobs:
  setup:
    name: DB Setup for ${{ github.event.inputs.environment || 'dev' }} environment
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: bahmni-cluster-dev
    steps:
      - run: |
          podTime=$(TZ=UTC date -d"22022-09-30T02:51:05Z" +%s)
          currentTime=$(TZ=UTC date +%s)
          diff=$($currentTime-$podTime)
          echo $currentTime,$podTime,$diff
      - uses: actions/checkout@v2
      - uses: mohan-13/versioning-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "Sample-12" > sample.txt
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Actions Cmmit"
          git push
      - run: ls -al
      
