name: Build and Publish OpenMRS
on:
  push:
    branches: [master]
jobs:
  helm-build-publish:
    name: Helm Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Helm Lint
        run: helm lint charts/sample1

