name: Database Setup
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for DB Setup'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - demo
jobs:
  setup:
    name: DB Setup for ${{ github.event.inputs.environment || 'dev' }} environment
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: bahmni-cluster-dev
    steps:
      - uses: actions/checkout@v2
      - run: |
          touch sample.txt
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Actions COmmit"
          git push
      - run: ls -al
