name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository : mohan-13/helm-charts
          ref: gh-pages
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          git add .
          git commit -m "generated"
          git push https://${{ secrets.PAT}}@github.com/:mohan-13/:helm-charts.git