name: Sample
on:
  push:
    branches:
      - master
      - 'release-*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  setup:
    name: DB Setup for ${{ github.event.inputs.environment || 'dev' }} environment
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: bahmni-cluster-dev
    steps:
      - run: |
          podTime=$(TZ=UTC date -d"2022-09-30T04:53:30Z" +%s)
          currentTime=$(TZ=UTC date +%s)
          diff=$((currentTime-podTime))
          date -u
          echo $currentTime,$podTime,$diff
      - uses: actions/checkout@v2
      - run: echo $GITHUB_REF
      
      
