name: Test
on:
  workflow_dispatch:
    inputs:
      enable_db_setup:
        description: 'Enable this to create datatbases'
        required: true
        type: boolean
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - run: echo ${{secrets.DEMO}}
    - run: echo ${{secrets.EMAIL123}}
    - run: echo "DEMO" > TEST
    - run: export VALUE=$(cat TEST) && echo $VALUE
    - id: sets-a-secret
      run: |
        the_secret="highly_secret"
        echo "::add-mask::$the_secret"
        echo "SECRET=$the_secret" >> $GITHUB_ENV
    - run: echo $SECRET
    - run: ls .github 
  
