name: Test
on:
  workflow_dispatch:
    inputs:
      enable_db_setup:
        description: 'Enable this to create datatbases'
        required: true
        type: boolean
        default: true
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        default: dev
        options:
          - dev
          - qa
          - demo

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    env:
      CLUSTER_NAME: bahmni-cluster-dev
      ENVIRONMENT: ${{ github.event.inputs.environment || 'dev'}}
      #ENVIRONMENT_URL: ${{ github.event.inputs.environment.lite.mybahmni.in != 'demo.lite.mybahmni.in' || lite.mybahmni.in
      ENVIRONMENT_URL: ${{ github.event.inputs.environment == 'demo' && 'lite.mybahmni.in' || format('{0}.{1}', github.event.inputs.environment, 'lite.mybahmni.in') }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - run: echo ${{secrets.DEMO}}
    - run: echo ${{secrets.EMAIL123}}
    - run: echo "DEMO" > TEST
    - run: export VALUE=$(cat TEST) && echo $VALUE
    - id: sets-a-secret
      run: |
        the_secret="highly_secret"
        echo "::add-mask::$the_secret"
        echo "SECRET=$the_secret" >> $GITHUB_ENV
    - run: echo $SECRET
    - run: ls .github/workflows
    - run: ls .github/workflows | cut -d '.' -f 1
    - run: ls .github/workflows | cut -d '.' -f 1 -f 2 
      shell: bash
    - run: echo ${{env.ENVIRONMENT_URL}}
  
