name: Test
on:
  workflow_dispatch:
    inputs:
      enable_db_setup:
        description: 'Set this to true to create datatbases'
        required: true
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - run: echo ${{secrets.DEMO}}
    - run: echo ${{secrets.EMAIL123}}
    - run: echo "DEMO" > TEST
    - run: export VALUE=$(cat TEST) && echo $VALUE
  
