name: Test
on:
  workflow_dispatch:
    inputs:
      enable_db_setup:
        description: 'Enable this to create datatbases'
        required: true
        type: boolean
        default: true
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        default: dev
        options:
          - dev
          - qa
          - demo
env:
  CLUSTER_NAME: bahmni-cluster-dev
  ENVIRONMENT: ${{ github.event.inputs.environment || 'dev'}}
  #ENVIRONMENT_URL: ${{ github.event.inputs.environment.lite.mybahmni.in != 'demo.lite.mybahmni.in' || lite.mybahmni.in
  ENVIRONMENT_DNS: ${{ github.event.inputs.environment || 'dev' == 'demo' && 'lite.mybahmni.in' || format('{0}.{1}', github.event.inputs.environment || 'dev', 'lite.mybahmni.in') }}
jobs:
  test:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment || 'dev'}}
      url: ${{ (github.event.inputs.environment || 'dev') == 'demo' && 'https://lite.mybahmni.in' || format('https://{0}.{1}', github.event.inputs.environment || 'dev', 'lite.mybahmni.in') }}
    steps:
    - run: echo ${{env.ENVIRONMENT_DNS}}
  
